config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
 
  resources :gast_platos
  resources :gast_postres
  resources :art_ttradicionales
  resources :art_cuchilleris
  resources :art_canteris
  resources :art_alfareris
  resources :adnd_playas
  resources :adnd_pnaturales
  resources :adnd_museos
  resources :act_ptematicos
  resources :act_senderismos
  resources :act_buceos
  resources :preguntasfrecuentes

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/act_ptematico.rb
class ActPtematico < ApplicationRecord
    validates :titulo,
        presence: {presence: true, message: ': ¡El título no puede estar en blanco, es un campo requerido!'}, 
        length: {maximum: 50, message: ': ¡El título debe de tener como máximo 50 caracteres!'},
        length: {minimum: 4, message: ': ¡El título debe de tener como mínimo 4 caracteres!'}
    validates :subtitulo,
        presence: {presence: true, message: ': ¡El subtítulo no puede estar en blanco, es un campo requerido!'}, 
        length: {maximum: 50, message: ': ¡El subtítulo debe de tener como máximo 50 caracteres!'},
        length: {minimum: 3, message: ': ¡El subtítulo debe de tener como mínimo 3 caracteres!'}
    validates :localizacion,
        presence: {presence: true, message: ': ¡La localización no puede estar en blanco, es un campo requerido!'}, 
        length: {maximum: 50, message: ': ¡La localización debe de tener como máximo 50 caracteres!'},
        length: {minimum: 5, message: ': ¡La localización debe de tener como mínimo 5 caracteres!'}
    validates :telefono,
        presence: {presence: true, message: ': ¡El teléfono no puede estar en blanco, es un campo requerido!'}, 
        format: {with: /\d{9}\z/i, message: ': ¡El teléfono debe contener 9 números!'},
        length: {maximum: 9, message: ': ¡El teléfono no puede contener más de 9 números!'}
    validates :sitioweb,
        presence: {presence: true, message: ': ¡El sitio web no puede estar en blanco, es un campo requerido!'}, 
        length: {minimum: 14, message: ': ¡El sitio web debe de tener como mínimo 14 caracteres!'}
end

app/controllers/act_ptematicos_controller.rb
class ActPtematicosController < ApplicationController
  before_action :set_act_ptematico, only: %i[ show edit update destroy ]

  # GET /act_ptematicos or /act_ptematicos.json
  def index
    @act_ptematicos = ActPtematico.all
  end

  # GET /act_ptematicos/1 or /act_ptematicos/1.json
  def show
  end

  # GET /act_ptematicos/new
  def new
    @act_ptematico = ActPtematico.new
  end

  # GET /act_ptematicos/1/edit
  def edit
  end

  # POST /act_ptematicos or /act_ptematicos.json
  def create
    @act_ptematico = ActPtematico.new(act_ptematico_params)

    respond_to do |format|
      if @act_ptematico.save
        format.html { redirect_to @act_ptematico, notice: "La nueva actividad de parques temáticos fue creada correctamente." }
        format.json { render :show, status: :created, location: @act_ptematico }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @act_ptematico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /act_ptematicos/1 or /act_ptematicos/1.json
  def update
    respond_to do |format|
      if @act_ptematico.update(act_ptematico_params)
        format.html { redirect_to @act_ptematico, notice: "La actividad de parques temáticos fue actualizada correctamente" }
        format.json { render :show, status: :ok, location: @act_ptematico }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @act_ptematico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /act_ptematicos/1 or /act_ptematicos/1.json
  def destroy
    @act_ptematico.destroy
    respond_to do |format|
      format.html { redirect_to act_ptematicos_url, notice: "La actividad de parques temáticos fue eliminada correctamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_act_ptematico
      @act_ptematico = ActPtematico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def act_ptematico_params
      params.require(:act_ptematico).permit(:titulo, :subtitulo, :localizacion, :telefono, :sitioweb)
    end
end

app/helpers/act_ptematicos_helper.rb
module ActPtematicosHelper
end

app/views/act_ptematicos/_form.html.erb
<%= form_with(model: act_ptematico) do |form| %>
  <% if act_ptematico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(act_ptematico.errors.count, "error") %> prohibió que se guarde esta entrada:</h2>

      <ul>
        <% act_ptematico.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="contenedor">
    <div class="field">
      <%= form.label "Título" %>
      <%= form.text_field :titulo %>
    </div>

    <div class="field">
      <%= form.label "Subtítulo" %>
      <%= form.text_field :subtitulo %>
    </div>

    <div class="field">
      <%= form.label "Localización" %>
      <%= form.text_field :localizacion %>
    </div>

    <div class="field">
      <%= form.label "Teléfono" %>
      <%= form.text_field :telefono, placeholder: 'XXX-XXX-XXX' %>
    </div>

    <div class="field">
      <%= form.label "Sitio web" %>
      <%= form.text_field :sitioweb, placeholder: 'https://ejemplo.com' %>
    </div>

    <div class="actions">
      <%= form.submit "Guardar" %>
    </div>
  </div>
<% end %>

app/views/act_ptematicos/edit.html.erb
<div class="contenedor">
    <h1>Editar Actividad de Parques temáticos: <%= @act_ptematico.subtitulo%></h1>

    <%= render 'form', act_ptematico: @act_ptematico %>
    <div class="enlace">
        <%= link_to 'Mostrar', @act_ptematico %>
        <%= link_to 'Atrás', act_ptematicos_path %>
    </div>
</div>

app/views/act_ptematicos/index.html.erb
<div class="contenedor">
<h1>Listado de sitios de Parques temáticos</h1>
  <table>
    <thead>
      <tr>
        <th>Título</th>
        <th>Subtítulo</th>
        <th>Localización</th>
        <th>Teléfono</th>
        <th>Sitio web</th>
        <th colspan="3">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @act_ptematicos.each do |act_ptematico| %>
        <tr>
          <td><%= act_ptematico.titulo %></td>
          <td><%= act_ptematico.subtitulo %></td>
          <td><%= act_ptematico.localizacion %></td>
          <td><%= act_ptematico.telefono %></td>
          <td><%= act_ptematico.sitioweb %></td>
          <td><%= link_to 'Mostrar', act_ptematico %></td>
          <td><%= link_to 'Editar', edit_act_ptematico_path(act_ptematico) %></td>
          <td><%= link_to 'Eliminar', act_ptematico, method: :delete, data: { confirm: '¿Está seguro de eliminar esta entrada?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <div class="enlace">
    <%= link_to 'Nueva entrada', new_act_ptematico_path %>
    <%= link_to 'Atrás', root_path %>
  </div>
  <p id="notice"><%= notice %></p>
</div>

app/views/act_ptematicos/new.html.erb
<div class="contenedor">
    <h1>Nueva Actividad de Parques temáticos</h1>

    <%= render 'form', act_ptematico: @act_ptematico %>
    <div class="enlcae">
        <%= link_to 'Atrás', act_ptematicos_path %>
    </div>
</div>

app/views/act_ptematicos/show.html.erb
<div class="contenedor">
  <h1>Parque temático: <%= @act_ptematico.subtitulo%></h1>

  <p>
    <strong>Título:</strong>
    <%= @act_ptematico.titulo %>
  </p>

  <p>
    <strong>Subtítulo:</strong>
    <%= @act_ptematico.subtitulo %>
  </p>

  <p>
    <strong>Localización:</strong>
    <%= @act_ptematico.localizacion %>
  </p>

  <p>
    <strong>Teléfono:</strong>
    <%= @act_ptematico.telefono %>
  </p>

  <p>
    <strong>Sitio web:</strong>
    <%= @act_ptematico.sitioweb %>
  </p>
  <div class="enlace">
    <%= link_to 'Editar', edit_act_ptematico_path(@act_ptematico) %>
    <%= link_to 'Atrás', act_ptematicos_path %>
  </div>

  <p id="notice"><%= notice %></p>
</div>