config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
 
  resources :gast_platos
  resources :gast_postres
  resources :art_ttradicionales
  resources :art_cuchilleris
  resources :art_canteris
  resources :art_alfareris
  resources :adnd_playas
  resources :adnd_pnaturales
  resources :adnd_museos
  resources :act_ptematicos
  resources :act_senderismos
  resources :act_buceos
  resources :preguntasfrecuentes

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/art_ttradicionale.rb
class ArtTtradicionale < ApplicationRecord
    validates :titulo,
        presence: {presence: true, message: ': ¡El título no puede estar en blanco, es un campo requerido!'}, 
        length: { maximum: 50, message: ': ¡El título debe de tener como máximo 50 caracteres!'},
        length: { minimum: 5, message: ': ¡El título debe de tener como mínimo 5 caracteres!'}
    validates :subtitulo,
        presence: {presence: true, message: ': ¡El subtítulo no puede estar en blanco, es un campo requerido!'},
        length: { maximum: 50, message: ': ¡El subtítulo debe de tener como máximo 50 caracteres!'},
        length: { minimum: 3, message: ': ¡El subtítulo debe de tener como mínimo 3 caracteres!'}
    validates :localizacion,
        presence: {presence: true, message: ': ¡La localización no puede estar en blanco, es un campo requerido!'},
        length: { maximum: 50, message: ': ¡La localización debe de tener como máximo 50 caracteres!'},
        length: { minimum: 5, message: ': ¡La localización debe de tener como mínimo 5 caracteres!'}
    validates :telefono,
        presence: {presence: true, message: ': ¡El teléfono no puede estar en blanco, es un campo requerido!'},
        format: { with: /\d{9}\z/i, message: ': ¡El teléfono debe contener 9 números!'},
        length: { maximum: 9, message: ': ¡El teléfono no puede contener más de 9 números!'}
end

app/controllers/art_ttradicionales_controller.rb
class ArtTtradicionalesController < ApplicationController
  before_action :set_art_ttradicionale, only: %i[ show edit update destroy ]

  # GET /art_ttradicionales or /art_ttradicionales.json
  def index
    @art_ttradicionales = ArtTtradicionale.all
  end

  # GET /art_ttradicionales/1 or /art_ttradicionales/1.json
  def show
  end

  # GET /art_ttradicionales/new
  def new
    @art_ttradicionale = ArtTtradicionale.new
  end

  # GET /art_ttradicionales/1/edit
  def edit
  end

  # POST /art_ttradicionales or /art_ttradicionales.json
  def create
    @art_ttradicionale = ArtTtradicionale.new(art_ttradicionale_params)

    respond_to do |format|
      if @art_ttradicionale.save
        format.html { redirect_to @art_ttradicionale, notice: "El nuevo sitio de Trajes tradicionales fue creado correctamente." }
        format.json { render :show, status: :created, location: @art_ttradicionale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @art_ttradicionale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /art_ttradicionales/1 or /art_ttradicionales/1.json
  def update
    respond_to do |format|
      if @art_ttradicionale.update(art_ttradicionale_params)
        format.html { redirect_to @art_ttradicionale, notice: "El sitio de Trajes tradicionales fue actualizado correctamente." }
        format.json { render :show, status: :ok, location: @art_ttradicionale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @art_ttradicionale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /art_ttradicionales/1 or /art_ttradicionales/1.json
  def destroy
    @art_ttradicionale.destroy
    respond_to do |format|
      format.html { redirect_to art_ttradicionales_url, notice: "El sitio de Trajes tradicionales fue eliminado correctamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art_ttradicionale
      @art_ttradicionale = ArtTtradicionale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def art_ttradicionale_params
      params.require(:art_ttradicionale).permit(:titulo, :subtitulo, :localizacion, :telefono, :informacion, :rss_facebook, :rss_instagram)
    end
end

app/helpers/art_ttradicionales_helper.rb
module ArtTtradicionalesHelper
end

app/views/art_ttradicionales/_form.html.erb
<%= form_with(model: art_ttradicionale) do |form| %>
  <% if art_ttradicionale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(art_ttradicionale.errors.count, "error") %> prohibió que se guarde este sitio:</h2>

      <ul>
        <% art_ttradicionale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="contenedor">
    <div class="field">
      <%= form.label "Título" %>
      <%= form.text_field :titulo %>
    </div>

    <div class="field">
      <%= form.label "Subtítulo" %>
      <%= form.text_field :subtitulo %>
    </div>

    <div class="field">
      <%= form.label "Localización" %>
      <%= form.text_field :localizacion %>
    </div>

    <div class="field">
      <%= form.label "Teléfono" %>
      <%= form.text_field :telefono, placeholder: 'XXX-XXX-XXX' %>
    </div>

    <div class="field">
      <%= form.label "Información" %>
      <%= form.url_field :informacion, placeholder: 'https://ejemplo.com' %>
    </div>

    <div class="field">
      <%= form.label "Página de Facebook" %>
      <%= form.url_field :rss_facebook, placeholder: 'https://www.facebook.com/Nombre' %>
    </div>

    <div class="field">
      <%= form.label "Página de Instagram" %>
      <%= form.url_field :rss_instagram, placeholder: 'https://www.instagram.com/Nombre' %>
    </div>

    <div class="actions">
      <%= form.submit "Guardar" %>
    </div>
  </div>
<% end %>

app/views/art_ttradicionales/edit.html.erb
<div class="contenedor">
    <h1>Editar sitio de Trajes tradicionales: <%= @art_ttradicionale.subtitulo%> </h1>

    <%= render 'form', art_ttradicionale: @art_ttradicionale %>
    <div class="enlace">
        <%= link_to 'Mostrar', @art_ttradicionale %> 
        <%= link_to 'Atrás', art_ttradicionales_path %>
    </div>
</div>

app/views/art_ttradicionales/index.html.erb
<div class="contenedor">
  <h1>Listado de Trajes Tradicionales</h1>

  <table>
    <thead>
      <tr>
        <th>Título</th>
        <th>Subtítulo</th>
        <th>Localización</th>
        <th>Teléfono</th>
        <th>Información</th>
        <th>Página de Facebook</th>
        <th>Página de Instagram</th>
        <th colspan="3">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @art_ttradicionales.each do |art_ttradicionale| %>
        <tr>
          <td><%= art_ttradicionale.titulo %></td>
          <td><%= art_ttradicionale.subtitulo %></td>
          <td><%= art_ttradicionale.localizacion %></td>
          <td><%= art_ttradicionale.telefono %></td>
          <td><%= art_ttradicionale.informacion %></td>
          <td><%= art_ttradicionale.rss_facebook %></td>
          <td><%= art_ttradicionale.rss_instagram %></td>
          <td><%= link_to 'Mostrar', art_ttradicionale %></td>
          <td><%= link_to 'Editar', edit_art_ttradicionale_path(art_ttradicionale) %></td>
          <td><%= link_to 'Eliminar', art_ttradicionale, method: :delete, data: { confirm: '¿Está seguro de eliminar esta entrada?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <div class="enlace">
    <%= link_to 'Nueva entrada', new_art_ttradicionale_path %>
    <%= link_to 'Atrás', root_path %>
  </div>

  <p id="notice"><%= notice %></p>
</div>

app/views/art_ttradicionales/new.html.erb
<div class="contenedor">
    <h1>Nuevo sitio de Trajes tradicionales</h1>

    <%= render 'form', art_ttradicionale: @art_ttradicionale %>
    <div class="enlace">
        <%= link_to 'Atrás', art_ttradicionales_path %>
    </div>
</div>

app/views/art_ttradicionales/show.html.erb
<div class="contenedor">
  <h1>Trajes tradicionales: <%= @art_ttradicionale.subtitulo%></h1>
  <p>
    <strong>Título:</strong>
    <%= @art_ttradicionale.titulo %>
  </p>

  <p>
    <strong>Subtítulo:</strong>
    <%= @art_ttradicionale.subtitulo %>
  </p>

  <p>
    <strong>Localización:</strong>
    <%= @art_ttradicionale.localizacion %>
  </p>

  <p>
    <strong>Teléfono:</strong>
    <%= @art_ttradicionale.telefono %>
  </p>

  <p>
    <strong>Información:</strong>
    <%= @art_ttradicionale.informacion %>
  </p>

  <p>
    <strong>Página de Facebook:</strong>
    <%= @art_ttradicionale.rss_facebook %>
  </p>

  <p>
    <strong>Página de Instagram:</strong>
    <%= @art_ttradicionale.rss_instagram %>
  </p>
  <div class="enlace">
    <%= link_to 'Editar', edit_art_ttradicionale_path(@art_ttradicionale) %>
    <%= link_to 'Atrás', art_ttradicionales_path %>
  </div>
  <p id="notice"><%= notice %></p>
</div>