config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
 
  resources :gast_platos
  resources :gast_postres
  resources :art_ttradicionales
  resources :art_cuchilleris
  resources :art_canteris
  resources :art_alfareris
  resources :adnd_playas
  resources :adnd_pnaturales
  resources :adnd_museos
  resources :act_ptematicos
  resources :act_senderismos
  resources :act_buceos
  resources :preguntasfrecuentes

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/preguntasfrecuente.rb
class Preguntasfrecuente < ApplicationRecord
    validates :pregunta,
        presence: true,
        presence: {presence: true, message: ': ¡La pregunta no puede estar en blanco, es un campo requerido!'}, 
        length: {maximum: 300, message: ': ¡La pregunta debe de tener como máximo 300 caracteres!'},
        length: {minimum: 6, message: ': ¡La pregunta debe de tener como mínimo 6 caracteres!'}
    validates :respuesta,
        presence: true,
        presence: {presence: true, message: ': ¡La respuesta no puede estar en blanco, es un campo requerido!'}, 
        length: {maximum: 400, message: ': ¡La respuesta debe de tener como máximo 400 caracteres!'},
        length: {minimum: 2, message: ': ¡La respuesta debe de tener como mínimo 2 caracteres!'}
end

app/controllers/preguntasfrecuentes_controller.rb
class PreguntasfrecuentesController < ApplicationController
  before_action :set_preguntasfrecuente, only: %i[ show edit update destroy ]

  # GET /preguntasfrecuentes or /preguntasfrecuentes.json
  def index
    @preguntasfrecuentes = Preguntasfrecuente.all
  end

  # GET /preguntasfrecuentes/1 or /preguntasfrecuentes/1.json
  def show
  end

  # GET /preguntasfrecuentes/new
  def new
    @preguntasfrecuente = Preguntasfrecuente.new
  end

  # GET /preguntasfrecuentes/1/edit
  def edit
  end

  # POST /preguntasfrecuentes or /preguntasfrecuentes.json
  def create
    @preguntasfrecuente = Preguntasfrecuente.new(preguntasfrecuente_params)

    respond_to do |format|
      if @preguntasfrecuente.save
        format.html { redirect_to @preguntasfrecuente, notice: "La nueva pregunta frecuente fue creada correctamente." }
        format.json { render :show, status: :created, location: @preguntasfrecuente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @preguntasfrecuente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preguntasfrecuentes/1 or /preguntasfrecuentes/1.json
  def update
    respond_to do |format|
      if @preguntasfrecuente.update(preguntasfrecuente_params)
        format.html { redirect_to @preguntasfrecuente, notice: "La pregunta frecuente fue actualizada correctamente." }
        format.json { render :show, status: :ok, location: @preguntasfrecuente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @preguntasfrecuente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preguntasfrecuentes/1 or /preguntasfrecuentes/1.json
  def destroy
    @preguntasfrecuente.destroy
    respond_to do |format|
      format.html { redirect_to preguntasfrecuentes_url, notice: "La pregunta frecuente fue eliminada correctamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preguntasfrecuente
      @preguntasfrecuente = Preguntasfrecuente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def preguntasfrecuente_params
      params.require(:preguntasfrecuente).permit(:pregunta, :respuesta)
    end
end

app/helpers/preguntasfrecuentes_helper.rb
module PreguntasfrecuentesHelper
end

app/views/preguntasfrecuentes/_form.html.erb
<%= form_with(model: preguntasfrecuente) do |form| %>
  <% if preguntasfrecuente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(preguntasfrecuente.errors.count, "error") %> prohibió que se guarde esta entrada:</h2>

      <ul>
        <% preguntasfrecuente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="contenedor">
    <div class="field">
      <%= form.label :pregunta %>
      <%= form.text_area :pregunta %>
    </div>

    <div class="field">
      <%= form.label :respuesta %>
      <%= form.text_area :respuesta %>
    </div>

    <div class="actions">
      <%= form.submit "Guardar" %>
    </div>
  </div>
<% end %>

app/views/preguntasfrecuentes/edit.html.erb
<div class="contenedor">
    <h1>Editar la Pregunta frecuente: <%= @preguntasfrecuente.id%></h1>

    <%= render 'form', preguntasfrecuente: @preguntasfrecuente %>
    <div class="enlace">
        <%= link_to 'Mostrar', @preguntasfrecuente %>
        <%= link_to 'Atrás', preguntasfrecuentes_path %>
    </div>
</div>

app/views/preguntasfrecuentes/index.html.erb
<div class="contenedor">
  <h1>Listado de Preguntas frecuentes</h1>

  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Pregunta</th>
        <th>Respuesta</th>
        <th colspan="3">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @preguntasfrecuentes.each do |preguntasfrecuente| %>
        <tr>
          <td><%= preguntasfrecuente.id%></td>
          <td><%= preguntasfrecuente.pregunta %></td>
          <td><%= preguntasfrecuente.respuesta %></td>
          <td><%= link_to 'Mostrar', preguntasfrecuente %></td>
          <td><%= link_to 'Editar', edit_preguntasfrecuente_path(preguntasfrecuente) %></td>
          <td><%= link_to 'Eliminar', preguntasfrecuente, method: :delete, data: { confirm: '¿Está seguro de eliminar esta entrada?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <div class="enlace">
    <%= link_to 'Nueva entrada', new_preguntasfrecuente_path %>
    <%= link_to 'Atrás', root_path %>
  </div>
  <p id="notice"><%= notice %></p>
</div>

app/views/preguntasfrecuentes/new.html.erb
<div class="contenedor">
    <h1>Nueva Pregunta frecuente</h1>

    <%= render 'form', preguntasfrecuente: @preguntasfrecuente %>
    <div class="enlace">
        <%= link_to 'Atrás', preguntasfrecuentes_path %>
    </div>
</div>

app/views/preguntasfrecuentes/show.html.erb
<div class="contenedor">
  <h1>Pregunta frecuente con id: <%= @preguntasfrecuente.id%> </h1>

  <p>
    <strong>Pregunta:</strong>
    <%= @preguntasfrecuente.pregunta %>
  </p>

  <p>
    <strong>Respuesta:</strong>
    <%= @preguntasfrecuente.respuesta %>
  </p>
  <div class="enlace">
    <%= link_to 'Editar', edit_preguntasfrecuente_path(@preguntasfrecuente) %>
    <%= link_to 'Atrás', preguntasfrecuentes_path %>
  </div>

  <p id="notice"><%= notice %></p>
</div>