config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
 
  resources :gast_platos
  resources :gast_postres
  resources :art_ttradicionales
  resources :art_cuchilleris
  resources :art_canteris
  resources :art_alfareris
  resources :adnd_playas
  resources :adnd_pnaturales
  resources :adnd_museos
  resources :act_ptematicos
  resources :act_senderismos
  resources :act_buceos
  resources :preguntasfrecuentes

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/gast_postre.rb
class GastPostre < ApplicationRecord
    validates :titulo,
        presence: {presence: true, message: ': ¡El título no puede estar en blanco, es un campo requerido!'}, 
        length: { maximum: 50, message: ': ¡El título debe de tener como máximo 50 caracteres!'},
        length: { minimum: 4, message: ': ¡El título debe de tener como mínimo 5 caracteres!'}
    validates :subtitulo,
        presence: {presence: true, message: ': ¡El subtítulo no puede estar en blanco, es un campo requerido!'},
        length: { maximum: 50, message: ': ¡El subtítulo debe de tener como máximo 50 caracteres!'},
        length: { minimum: 3, message: ': ¡El subtítulo debe de tener como mínimo 3 caracteres!'}
    validates :localizacion,
        presence: {presence: true, message: ': ¡La localización no puede estar en blanco, es un campo requerido!'},
        length: { maximum: 50, message: ': ¡La localización debe de tener como máximo 50 caracteres!'},
        length: { minimum: 5, message: ': ¡La localización debe de tener como mínimo 5 caracteres!'}
    validates :telefono,
        presence: {presence: true, message: ': ¡El teléfono no puede estar en blanco, es un campo requerido!'},
        format: { with: /\d{9}\z/i, message: ': ¡El teléfono debe contener 9 números!'},
        length: { maximum: 9, message: ': ¡El teléfono no puede contener más de 9 números!'}

end

app/controllers/gast_postres_controller.rb
class GastPostresController < ApplicationController
  before_action :set_gast_postre, only: %i[ show edit update destroy ]

  # GET /gast_postres or /gast_postres.json
  def index
    @gast_postres = GastPostre.all
  end

  # GET /gast_postres/1 or /gast_postres/1.json
  def show
  end

  # GET /gast_postres/new
  def new
    @gast_postre = GastPostre.new
  end

  # GET /gast_postres/1/edit
  def edit
  end

  # POST /gast_postres or /gast_postres.json
  def create
    @gast_postre = GastPostre.new(gast_postre_params)

    respond_to do |format|
      if @gast_postre.save
        format.html { redirect_to @gast_postre, notice: "El nuevo sitio de postres típicos fue creado correctamente." }
        format.json { render :show, status: :created, location: @gast_postre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gast_postre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gast_postres/1 or /gast_postres/1.json
  def update
    respond_to do |format|
      if @gast_postre.update(gast_postre_params)
        format.html { redirect_to @gast_postre, notice: "El sitio de postres típicos fue actualizado correctamente." }
        format.json { render :show, status: :ok, location: @gast_postre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gast_postre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gast_postres/1 or /gast_postres/1.json
  def destroy
    @gast_postre.destroy
    respond_to do |format|
      format.html { redirect_to gast_postres_url, notice: "El sitio de postres típicos fue eliminado correctamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gast_postre
      @gast_postre = GastPostre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gast_postre_params
      params.require(:gast_postre).permit(:titulo, :subtitulo, :localizacion, :telefono, :rss_facebook, :rss_instagram, :informacion)
    end
end

app/helpers/gast_postres_helper.rb
module GastPostresHelper
end

app/views/gast_postres/_form.html.erb
<%= form_with(model: gast_postre) do |form| %>
  <% if gast_postre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gast_postre.errors.count, "error") %> prohibió que se guarde este sitio de postres típicos:</h2>

      <ul>
        <% gast_postre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="contenedor">
    <div class="field">
      <%= form.label "Título" %>
      <%= form.text_field :titulo %>
    </div>

    <div class="field">
      <%= form.label "Subtítulo" %>
      <%= form.text_field :subtitulo %>
    </div>

    <div class="field">
      <%= form.label "Localización" %>
      <%= form.text_field :localizacion %>
    </div>

    <div class="field">
      <%= form.label "Teléfono" %>
      <%= form.text_field :telefono, placeholder: 'XXX-XXX-XXX' %>
    </div>

    <div class="field">
      <%= form.label "Página de Facebook" %>
      <%= form.url_field :rss_facebook, placeholder: 'https://www.facebook.com/Nombre' %>
    </div>

    <div class="field">
      <%= form.label "Página de Instagram" %>
      <%= form.url_field :rss_instagram, placeholder: 'https://www.instagram.com/Nombre' %>
    </div>

    <div class="field">
      <%= form.label "Información" %>
      <%= form.url_field :informacion, placeholder: 'https://ejemplo.com' %>
    </div>

    <div class="actions">
      <%= form.submit "Guardar"%>
    </div>
  </div>
<% end %>

app/views/gast_postres/edit.html.erb
<div class="contenedor">
    <h1>Editar sitio de postres típicos: <%= @gast_postre.subtitulo%> </h1>

    <%= render 'form', gast_postre: @gast_postre %>
    <div class="enlace">
        <%= link_to 'Mostrar', @gast_postre %> 
        <%= link_to 'Atrás', gast_postres_path %>
    </div>
</div>

app/views/gast_postres/index.html.erb
<div class="contenedor">
  <h1>Listado de sitios de Postres típicos en Gran Canaria</h1>

  <table>
    <thead>
      <tr>
        <th>Título</th>
        <th>Subtítulo</th>
        <th>Localización</th>
        <th>Teléfono</th>
        <th>Página de Facebook</th>
        <th>Página de Instagram</th>
        <th>Información</th>
        <th colspan="3">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @gast_postres.each do |gast_postre| %>
        <tr>
          <td><%= gast_postre.titulo %></td>
          <td><%= gast_postre.subtitulo %></td>
          <td><%= gast_postre.localizacion %></td>
          <td><%= gast_postre.telefono %></td>
          <td><%= gast_postre.rss_facebook %></td>
          <td><%= gast_postre.rss_instagram %></td>
          <td><%= gast_postre.informacion %></td>
          <td><%= link_to 'Mostrar', gast_postre %></td>
          <td><%= link_to 'Editar', edit_gast_postre_path(gast_postre) %></td>
          <td><%= link_to 'Eliminar', gast_postre, method: :delete, data: { confirm: '¿Está seguro de eliminar esta entrada?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <div class="enlace">
    <%= link_to 'Nueva entrada', new_gast_postre_path %>
    <%= link_to 'Atrás', root_path %>
  </div>
  <p id="notice"><%= notice %></p>
</div>

app/views/gast_postres/new.html.erb
<div class="contenedor">
    <h1>Nuevo sitio de Postres típicos en Gran Canaria</h1>

    <%= render 'form', gast_postre: @gast_postre %>

    <div class="enlace">
        <%= link_to 'Atrás', gast_postres_path %>
    </div>
</div>

app/views/gast_postres/show.html.erb
<div class="contenedor">
<  <h1>Sitio de Postres típicos: <%= @gast_postre.subtitulo%></h1>
  <p>
    <strong>Título:</strong>
    <%= @gast_postre.titulo %>
  </p>

  <p>
    <strong>Subtítulo:</strong>
    <%= @gast_postre.subtitulo %>
  </p>

  <p>
    <strong>Localización:</strong>
    <%= @gast_postre.localizacion %>
  </p>

  <p>
    <strong>Teléfono:</strong>
    <%= @gast_postre.telefono %>
  </p>

  <p>
    <strong>Página de Facebook:</strong>
    <%= @gast_postre.rss_facebook %>
  </p>

  <p>
    <strong>Página de Instagram:</strong>
    <%= @gast_postre.rss_instagram %>
  </p>

  <p>
    <strong>Información:</strong>
    <%= @gast_postre.informacion %>
  </p>
  
  <div class="enlace">
    <%= link_to 'Editar', edit_gast_postre_path(@gast_postre) %> |
    <%= link_to 'Atrás', gast_postres_path %>
  </div>
  <p id="notice"><%= notice %></p>
</div>